### ISSUE TITLE
Add `.processor` to the public API

### ISSUE THREAD

**Issue by dkreft** [jasonpincin/concurrent-queue#1]
Hi,

Would you consider adding `.processor` to the public API for this package? It's currently not documented as part of the public API which leads me to believe that it's a private implementation detail (and thus not safe to use directly). And since it's not part of the public API, there's no safe way to validate in a unit test that I've passed the correct argument to `.process()`.

Actually, what would be really awesome is if this actually used a prototype so that by using stubs, I can check to make sure that the correct arguments were passed to the various functions rather than relying upon assumptions about how things are stored internally after I pass them to you. But I recognize that'd be a much bigger change. :-)

Thanks,

-dan

**Comment by jasonpincin** [comment]
Thanks for reporting this @dkreft - I will add it to the documentation as it should have been there. Consider it public.

**Comment by jasonpincin** [comment]
Done.
